"""playlist-features-column-playlist_id-to-spotify_playlist_id

Revision ID: 47fad346eb85
Revises: 1baac5003eed
Create Date: 2024-05-11 00:16:30.537025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fad346eb85'
down_revision: Union[str, None] = '1baac5003eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists_features', sa.Column('spotify_playlist_id', sa.String(), nullable=False))
    op.drop_index('ix_playlists_features_playlist_id', table_name='playlists_features')
    op.create_index(op.f('ix_playlists_features_spotify_playlist_id'), 'playlists_features', ['spotify_playlist_id'], unique=True)
    op.drop_column('playlists_features', 'playlist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists_features', sa.Column('playlist_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_playlists_features_spotify_playlist_id'), table_name='playlists_features')
    op.create_index('ix_playlists_features_playlist_id', 'playlists_features', ['playlist_id'], unique=True)
    op.drop_column('playlists_features', 'spotify_playlist_id')
    # ### end Alembic commands ###
