"""all-models

Revision ID: 8aaed0d1aacb
Revises: 
Create Date: 2024-05-12 06:23:28.255561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aaed0d1aacb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Numeric(), nullable=False),
    sa.Column('liveness', sa.Numeric(), nullable=False),
    sa.Column('tempo', sa.Numeric(), nullable=False),
    sa.Column('speechiness', sa.Numeric(), nullable=False),
    sa.Column('acousticness', sa.Numeric(), nullable=False),
    sa.Column('instrumentalness', sa.Numeric(), nullable=False),
    sa.Column('danceability', sa.Numeric(), nullable=False),
    sa.Column('loudness', sa.Numeric(), nullable=False),
    sa.Column('evaluation_score', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_weights_id'), 'model_weights', ['id'], unique=False)
    op.create_table('playlists_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(), nullable=False),
    sa.Column('energy', sa.Numeric(), nullable=False),
    sa.Column('liveness', sa.Numeric(), nullable=False),
    sa.Column('tempo', sa.Numeric(), nullable=False),
    sa.Column('speechiness', sa.Numeric(), nullable=False),
    sa.Column('acousticness', sa.Numeric(), nullable=False),
    sa.Column('instrumentalness', sa.Numeric(), nullable=False),
    sa.Column('danceability', sa.Numeric(), nullable=False),
    sa.Column('loudness', sa.Numeric(), nullable=False),
    sa.Column('valence', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_features_id'), 'playlists_features', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_features_spotify_playlist_id'), 'playlists_features', ['spotify_playlist_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_spotify_id'), 'users', ['spotify_id'], unique=True)
    op.create_table('tplaylists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tplaylists_id'), 'tplaylists', ['id'], unique=False)
    op.create_index(op.f('ix_tplaylists_spotify_playlist_id'), 'tplaylists', ['spotify_playlist_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tplaylists_spotify_playlist_id'), table_name='tplaylists')
    op.drop_index(op.f('ix_tplaylists_id'), table_name='tplaylists')
    op.drop_table('tplaylists')
    op.drop_index(op.f('ix_users_spotify_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_playlists_features_spotify_playlist_id'), table_name='playlists_features')
    op.drop_index(op.f('ix_playlists_features_id'), table_name='playlists_features')
    op.drop_table('playlists_features')
    op.drop_index(op.f('ix_model_weights_id'), table_name='model_weights')
    op.drop_table('model_weights')
    # ### end Alembic commands ###
