"""model-weights

Revision ID: d25a5016199c
Revises: 47fad346eb85
Create Date: 2024-05-12 00:12:02.248781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25a5016199c'
down_revision: Union[str, None] = '47fad346eb85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Numeric(), nullable=False),
    sa.Column('liveness', sa.Numeric(), nullable=False),
    sa.Column('tempo', sa.Numeric(), nullable=False),
    sa.Column('speechiness', sa.Numeric(), nullable=False),
    sa.Column('acousticness', sa.Numeric(), nullable=False),
    sa.Column('instrumentalness', sa.Numeric(), nullable=False),
    sa.Column('danceability', sa.Numeric(), nullable=False),
    sa.Column('loudness', sa.Numeric(), nullable=False),
    sa.Column('evaluation_score', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_weights_id'), 'model_weights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_weights_id'), table_name='model_weights')
    op.drop_table('model_weights')
    # ### end Alembic commands ###
